apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-deployment
  labels:
    app: devops
spec:
  replicas: {{ .Values.deployment.replica }}
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: "true"
      labels:
        app: devops
    spec:
      containers:
        - name: devops
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.http.port }}
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT # Needed for traces to work.
              value: "http://$(HOST_IP):4317"
            - name: OTEL_SERVICE_NAME           # Service name to be used by the tracer
              value: "devops-project"
